INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (1,'Firman Fauzi Desviya',+6281320366992,'Ekastuti Sekarmirah',NULL,'Jl. Turangga Timur No.16A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (2,'Yudi Haryadi',NULL,'Rd. Rieka Ruchyanti Ruchiyat',NULL,'Jl. Sekelimus VII No.27');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (3,'Indra Herdiansyah',+6285222254513,'Windy Afriani',+6287822042203,'Jl. Perkebunan II No.20');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (4,'Prihandhanu Mukti Pratomo',+62811237488,'Mayang Ambarsari',+6281321110265,'Jl. Saluyu C4 Blok 2F No.187');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (5,'Nugy Nugraha',+62811237488,'Fathia Soraya',+628112234555,'Jl. Sekelimus VIII No.21');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (6,'Nugy Nugraha',NULL,'Fathia Soraya',+628112234555,'Jl. Sekelimus VIII No.21');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (7,'R.M Rahmat Muharam',NULL,'Anty Novianty',+6285975984632,'Jl. Kacapiring No.48/122');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (8,'M.Pahlevi',+6281563826058,'Puteri Patriana',+6287722164332,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (9,'Riga Suryamahardika',+6281930301982,'Donna Cempawaty',+62818217193,'Cluster Pawenang Blok B08');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (10,'Audie Aditya',NULL,'Tri Hani Astuti',NULL,'Jl. Karapitan No.26');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (11,'NN',NULL,'Nia Kaniawati',NULL,'Jl. Cilengkrang II No.179');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (12,'Moch. Syahrulloh',+6287823297678,'Yuni Erlina',+6281281823318,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (13,'Dadan Riswan',+6281321697692,'Resi Melinda',NULL,'Jl. Turangga Timur No.27/115');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (14,'Muhammad Alie',+628562184006,'Yuliana',+628157110010,'Jl. Baja No.14');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (15,'Rian Kuswardani',+628562184006,'Atiek Rahmawati',+628112214361,'Jl. Taman Palem No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (16,'Rian Kuswardani',+6281802119975,'Atiek Rahmawati',+628112214361,'Jl. Taman Palem No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (17,'Muhammad Hilfiansyah',+6282118888985,'Indri Angriani',+6281809722247,'Jl. Sadakeling No.59');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (18,'Reycke W.Taulo',+6282118888985,'Anti Maryanti',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (19,'Reycke W.Taulo',+6281320366992,'Anti Maryanti',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (20,'Firman Fauzi Desviya',NULL,'Ekastuti Sekarmirah',NULL,'Jl. Turangga Timur No.16A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (21,'Gadus Afrizal',+6281320366992,'Rini Handayani',+6281220833697,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (22,'Firman Fauzi Desviya',NULL,'Ekastuti Sekarmirah',NULL,'Jl. Turangga Timur No.16A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (23,'Halami',NULL,'Rizki Chrisulianti',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (24,'Budi Setiawan',NULL,'Eva Maylora',NULL,'Jl. Rengkong No.2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (25,'Budi Setiawan',NULL,'Eva Maylora',NULL,'Jl. Rengkong No.2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (26,'Satrio Budyo Amisani',+628222267525,'Citra Rizana',+628112127506,'Komp D''Amerta Blok D-11 No.11');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (27,'Satrio Budyo Amisani',+62818330799,'Citra Rizana',+628112127506,'Komp. D''Amerta Blok D-11 No.11');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (28,'Aldino Pradana',+62818330799,'Anne Yuliana',+628112230799,'Jl. Mayang Cinde No.1a');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (29,'Aldino Pradana',+6281320643151,'Anne Yuliana',+628112230799,'Jl. Mayang Cinde No.1A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (30,'Sunarya',NULL,'Siti Sofiah',NULL,'Permata Kopo Jl. Rubby C2 No.10');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (31,'Gumilar Satria Agung',+6281563826058,'Tia Novianti',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (32,'Riga Suryamahardika',NULL,'Donna Cempawaty',+62818217193,'Cluster Pawenang Blok B08');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (33,'Michael Salakay',+628112245655,'Ratih Arsianti',+628122157258,'Jl. Meteor Timur I Blok A2 No.261');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (34,'Ishak Hirawan',+628112245655,'Novi Nurwidyawati',+628122043456,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (35,'Ishak Hirawan',+628112245655,'Novi Nurwidyawati',+628122043456,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (36,'Ishak Hirawan',NULL,'Novi Nurwidyawati',+628122043456,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (37,'Bayu',NULL,'Melly Amalia',NULL,'Komplek Palem Permai Jl. Taman Palem No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (38,'Bayu',NULL,'Melly Amalia',NULL,'Komplek Palem Permai Jl. Taman Palem No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (39,'Erwin Yogaswara',NULL,'Devi Saftrianti',+628122175846,'Jl. Batununggal Abadi VI No.4');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (40,'Bambang Setiadi',+6287722559060,'Pisce Arida Nur Amal',+6281546800699,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (41,'Arman Wahyudi',NULL,'Ria Mulyasari',+6287822458644,'Jl. Waas A No.5');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (42,'Gina Samudra',+6281321431286,'Chyntia Isti Destiandriati',+6285723560333,'Komplek Bumi Asri Cilengkrang No.3');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (43,'Asep Tatang',+6281321431286,'Nyayu Susi Fauziah',+6281320068616,'Jl. Arhanudri No.2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (44,'Asep Tatang',NULL,'Nyayu Susi Fauziah',+6281320068616,'Jl. Arhanudri No.2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (45,'Januar Nurhadiyat',+6282140014003,'Nova Noveristi Aulia Safitri',+6289656508762,'Jl. SPAI Mama Leube No.5');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (46,'Daniel Arya Pradana',NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (47,'Luqman Nur Ekaprasetia',+6281322284692,'Elok Ratih Novaria',+628117681181,'Jl. Teluk Buyung Kaler No.1');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (48,'Dicky Ferdian Nugraha',+6281322284692,'Kiki Rahmawati',+6282126837997,'Jl. Waluh No.4');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (49,'Dicky Ferdian Nugraha',NULL,'Kiki Rahmawati',+6282126837997,'Jl. Waluh No.4');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (50,'Edi Prayitno',NULL,'Ema Hermawati',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (51,'Ida Bagus Sutawijaya',+628122375247,'Deviana Yuanitasari',+6281223438276,'Jl. Rakata No.63');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (52,'Hilman Muhammad Taufan',NULL,'Diny Rosalina',NULL,'Jl. Riung Hegar II No.11A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (53,'Yusuf Malik Saleh',NULL,'Rarasati',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (54,'Henry Bayuaji',NULL,'Fitrieza Windayani',+62817435913,'Jl. Wirawan Raya No.9');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (55,'Henry Bayuaji',NULL,'Fitrieza Windayani',+62817435913,'Jl. Wirawan Raya No.9');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (56,'Aulia Fithrajaya',NULL,'Yussie Widyana',+6282280220079,'Jl. Giri Rahayu I No.10');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (57,'Eka Permana Habibillah',NULL,'Isnayani',+6289655006310,'Jl. Logam 10');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (58,'Arief',NULL,'Ayu Kusumawati',+628986333338,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (59,'Arief',NULL,'Ayu Kusumawati',+628986333338,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (60,'Diki Musodiki',NULL,'Siti Yulia',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (61,'Wisnu Umbara',NULL,'Mira Marsyana',+6281322761539,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (62,'Wisnu Umbara',NULL,'Mira Marsyana',+6281322761539,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (63,'M. Irsan',NULL,'Amanda Wisudya',+6281320367899,'Jl. Cikaso Selatan No.21');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (64,'Ahmad Rifai',+6282115566664,'Erni Sumiati Indriani',NULL,'Jl. 17 Agustus I No.5');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (65,'Wendy Priandani',NULL,'Artin Garfiani',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (66,'Januar Nurhadiyat',NULL,'Nova Noveristi Aulia Safitri',+6289656508762,'Jl. SPAI Mama Leube No.5');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (67,'Andika Maryuniawan',+6281319197887,'Sentari Trianawati',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (68,'Jehezkiel Lofani Mengko',NULL,'Winny Herlina Mega',NULL,'Jl. Antapani XII No.3');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (69,'Muhammad Natsir',NULL,'Fifi Nurul Aisiyah',+6285223028821,'Jl. Sumenep No.48');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (70,'Yanuar Ferdian',+628122249218,'Erni Kartika',+62811219569,'Komp. Mitra Resident No. C7');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (71,'Didin Baheramsyah',NULL,'Irma Yuli Agustina',+6281222799388,'Jl. Cukang Kawung No.28');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (72,'Luqman Nur Ekaprasetia',NULL,'Elok Ratih Novaria',NULL,'Jl. Teluk Buyung Kaler No.1');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (73,'Widyanto Nugroho',NULL,'Evana Ika Putri',+6281222229850,'Jl. Tegal No.11');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (74,'Mohamad Arief Oktavian',NULL,'Sulistyowati',NULL,'Jl. Graha Asih III No.1');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (75,'Mohamad Arief Oktavian',NULL,'Sulistyowati',NULL,'Jl. Graha Asih III No.1');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (76,'Frans Tanujaya',NULL,'Diana',NULL,'Jl. Aceh No.18');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (77,'Edwin',+6281221374141,'Vina Andreany',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (78,'Mochamad Gunawan Wibisono',+6281221374141,'Leni M',NULL,'Jl. Sanggar Kencana XIV No.25');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (79,'Mochamad Gunawan Wibisono',NULL,'Leni Susanti',NULL,'Jl Sanggar Kencana XIV No.25');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (80,NULL,+6282331708900,'Fifi Refitasari',+6282185880996,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (81,'Aries Budiman',+6285794105361,'Lanny Maulany',NULL,'Jl. Kiaracondong Barat No.50/126D');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (82,'Vicky',NULL,'Ratna',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (83,'Reginaldy Gustiansyah Setya',NULL,'Ardana Reswari',+628112538821,'Jl. Cigadung Selatan Dalam II No.60');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (84,'Asep Sanjaya',NULL,'Tri Hari Lestari',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (85,'Kenya Gansar P',NULL,'Dipta',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (86,'Maruly Abraham Syah',NULL,'Irene Susanti',+628179276452,'Jl. Batik Jogja No.38');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (87,'Ihsan Herman',NULL,'Wisa Yustina Alani',+6281223930033,'Jl. Waluh No.2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (88,'Muhammad Natsir',+6285268005123,'Fifi Nurul Aisiyah',+6285223028821,'Jl. Sumenep No.48');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (89,'Rico Ramadhan',NULL,'Rika Eriyanti',NULL,'Kp. Kadaung');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (90,NULL,NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (91,'Yudha Setiawan',+6281290988988,'Rulan Danar Dini',+6281112019000,'Jl. Patrakomala No.35');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (92,'Adhy Ade Andriansyah',+6282331708900,'Lusi Aprianisari',+6281221379578,'Jl. Haruman 20 A');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (93,'Aries Budiman',NULL,'Lanny Maulany',NULL,'Jl. Kiaracondong Barat No.50/126D');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (94,'Suripto',NULL,'Iin Komalasari',+62813201097955,'Jl. Turangga Timur No.4');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (95,'Lucky Lukman Riadi',NULL,'Linlin Maulina',+6281221016565,'Jl. Puri Dago Asri No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (96,NULL,NULL,'Siti Nurbaiti',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (97,NULL,NULL,'Sri Komalasari',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (98,'Bayu Ekajatnika Putra',+6281394532345,'Ria Amalia',+6281809351593,'Jl. Purbanamik No. C19 Guruminda');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (99,'Rizal Rismandani',NULL,'Restu Hartati',NULL,'Komp. Permata Cimahi A3 No.4 Bandung Barat');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (100,'Pindy Purnama Arisca',+6281910405034,'Kurniawati',NULL,'Jl. H. Yasin VI No.8');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (101,'Anto Adrian',NULL,'Rizka Martha',NULL,'Jl. Mars Barat VI No.22');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (102,'Andi Abdul Mughnij',+6282218189229,'Willma Fauzzia',+6281214300706,'Jl. Komp. Bumi Asri , Jl. Kiara Asri VII No.7');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (103,'Mumtaz Lazuardhi',NULL,'Susan Santiawati',NULL,'Komp. Cibaduyut Permai, Jl. Plaosan F2');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (104,NULL,NULL,'Sazkia R Gaziscani',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (105,NULL,NULL,'Astrie Yumeisa',+6281320321310,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (106,NULL,NULL,'Astrie Yumeisa',+6281320321310,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (107,NULL,NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (108,NULL,NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (109,'Irvan Octavian',NULL,'Siti Hajar Mahsa',NULL,'Jl. Kayu Agung I Blok C No.59');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (110,'Irvan Octavian',NULL,'Siti Hajar Mahsa',NULL,'Jl. Kayu Agung I Blok C No.59');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (111,'Wandy Ferdian',NULL,'Azriefa NF',+628112130436,'Komp. Nata Endah Blok N No.3 Cihanjuang');
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (112,NULL,NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (113,NULL,+6281323068871,'Pupung Puji P.',NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (114,'Faizal Pujayanto',NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (115,'Mulya',NULL,NULL,NULL,NULL);
INSERT INTO orangtuas(id,nama_ayah,no_telepon_ayah,nama_ibu,no_telepon_ibu,alamat) VALUES (116,NULL,NULL,NULL,NULL,NULL);
